version: "3.9"

services:
    ocr_api_srv:
        image: fast_ocr
        container_name: ocr_api_srv
        restart: always
        environment:
          - UPLOAD_DIR=/vol/web/uploads
        volumes:
          - ./app:/code
          - ${STATIC_ROOT_REL}:/vol/web/static
          - ${MEDIA_ROOT_REL}:/vol/web/uploads
        
        ports:
          - "5000:5000"

