version: "3.9"

x-services-volumes: &services-volumes
  - ./app:/code:ro,cached
  - ${MEDIA_ROOT_REL}:/vol/web/uploads
  - ${STATIC_ROOT_REL}:/vol/web/static

services:
  db:
      # container_name: postgresql_db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      # - POSTGRES_DB=image
      - POSTGRES_DB=${DB_NAME}

  ocr_api_srv:
    image: fast_ocr
    # build:
    #   context: .
    container_name: ocr_api_srv
    restart: always
    depends_on:
      - db
    command: bash -c "alembic upgrade head && python main.py"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${DB_NAME}
      - UPLOAD_DIR=/vol/web/uploads
      - DATABASE_HOST=db
    volumes: *services-volumes
    ports:
      - "5000:5000"
    
  proxy:
  # build: 
  #    context: ./proxy
    image: ocr_nginx
    # container_name: nginx_proxy
    restart: always
    depends_on: 
      - ocr_api_srv 
    ports: 
      - ${NGINX_LESTEN_PORT}:80
    volumes: *services-volumes

