#!/bin/bash

docker run -d \
    -p 5432:5432 \
    -e POSTGRES_PASSWORD=1234 \
    -e POSTGRES_USER=user \
    -e POSTGRES_DB=image \
    postgres

docker run -d -p 80:80 -e PGADMIN_DEFAULT_EMAIL=a@a.com -e PGADMIN_DEFAULT_PASSWORD=1111 dpage/pgadmin4:latest

# -e PGDATA=/var/lib/postgresql/data/pgdata \ */
# -v /custom/mount:/var/lib/postgresql/data \

